### ISSUE TITLE
Flaky test: mangrove-solidity - test:polygon-mainnet - Deploy offerProxy

### ISSUE THREAD

**Issue by espendk** [mangrovedao/mangrove#109]
The test "Deploy offerProxy" in the test:polygon-mainnet suite of the mangrove-solidity package, occasionally fails.

Here are some failed runs:

**2022-01-04 & 2022-03-07:**
```
  1) Deploy offerProxy
       Offer proxy on aave:
     AssertionError: Incorrect DAI lending balance on aave (truncated at 4 decimals):
Expected: 200.0
Given: 1000.000005452532923067

      at assertAlmost (lib/libcommon.js:312:3)
      at Object.expectAmountOnLender (lib/libcommon.js:684:5)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at runNextTicks (internal/process/task_queues.js:64:3)
      at listOnTimeout (internal/timers.js:526:9)
      at processTimers (internal/timers.js:500:7)
      at async execLenderStrat (test/Exec/lenderStrats.js:53:3)
      at async Context.<anonymous> (test/test-offerProxy.js:147:5)
```
https://github.com/mangrovedao/mangrove/runs/4701792082?check_suite_focus=true#step:11:298
https://github.com/mangrovedao/mangrove/runs/5441677686?check_suite_focus=true#step:11:368

**2022-01-08:**
```
  1) Deploy offerProxy
       Offer proxy on aave:
     AssertionError: Snipe failed
      at Object.snipeSuccess (lib/libcommon.js:522:3)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async execLenderStrat (test/Exec/lenderStrats.js:31:31)
      at async Context.<anonymous> (test/test-offerProxy.js:147:5)
```
https://github.com/mangrovedao/mangrove/runs/4747252916?check_suite_focus=true#step:11:293

**2022-01-10:**
```
  1) Deploy offerProxy
       Offer proxy on aave:
     AssertionError: Incorrect DAI lending balance on aave (truncated at 4 decimals):
Expected: 200.0
Given: 1000.000004543777414989

      at assertAlmost (lib/libcommon.js:312:3)
      at Object.expectAmountOnLender (lib/libcommon.js:684:5)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at runNextTicks (internal/process/task_queues.js:64:3)
      at listOnTimeout (internal/timers.js:526:9)
      at processTimers (internal/timers.js:500:7)
      at async execLenderStrat (test/Exec/lenderStrats.js:53:3)
      at async Context.<anonymous> (test/test-offerProxy.js:147:5)
```
https://github.com/mangrovedao/mangrove/runs/4767589463?check_suite_focus=true#step:11:298

**2022-03-03:**
```
Deploy offerProxy
  ❌ Offer proxy on aave
	Snipe failed

AssertionError: Snipe failed
    at Object.snipeSuccess (lib/libcommon.js:540:3)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async execLenderStrat (test/Exec/lenderStrats.js:32:31)
    at async Context.<anonymous> (test/test-offerProxy.js:153:5)
```

**Comment by jkrivine** [comment]
should be OK now @espendk ?

**Comment by espendk** [comment]
yeah, the fix you made in #110 looks like it could fix the root cause - `wait(0)` will defo cause problems if you want to make sure tx is mined before proceeding.

**Comment by espendk** [comment]
Failed again yesterday, so re-opening this.

**Comment by espendk** [comment]
There are still some issues with tx's not being waited for. But as the tests are in JS it's difficult to find all the cases; It would be easier to ensure all promises were awaited, if the code was ported to TypeScript.

I'll fix the cases I found and keep this open for now in case more failures pop up.

**Comment by dontrolle** [comment]
As far as I can see all examples here relate to former sub-repo `mangrove-solidity` tests, which have now been moved and ported to Foundry. Hence, I'm closing this as deprecated. Please reopen, if still needed.
