### ISSUE TITLE
Cannot connect to Mangrove using `WebSocketProvider`

### ISSUE THREAD

**Issue by jkrivine** [mangrovedao/mangrove#112]
The following code:
```javascript
  const provider = new ethers.providers.WebSocketProvider(
    hre.network.config.url
  );

 // this works
  const wallet = new ethers.Wallet(
    process.env["PRIVATE_KEY"],
    provider
  );

// this doesn't
  const MgvAPI = await Mangrove.connect({
    provider: provider,
    privateKey: wallet.privateKey,
  });
```
produces an error:
```
/Users/jkrivine/Documents/git/blockchain/mangrove/packages/mangrove-solidity/node_modules/@ethersproject/providers/src.ts/websocket-provider.ts:107
                        error = new Error(result.error.message || "unknown error");
                                ^
Error: Invalid request
    at WebSocketProvider._this._websocket.onmessage (/Users/jkrivine/Documents/git/blockchain/mangrove/packages/mangrove-solidity/node_modules/@ethersproject/providers/src.ts/websocket-provider.ts:107:33)
    at WebSocket.onMessage (/Users/jkrivine/Documents/git/blockchain/mangrove/packages/mangrove-solidity/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (node:events:390:28)
    at Receiver.receiverOnMessage (/Users/jkrivine/Documents/git/blockchain/mangrove/packages/mangrove-solidity/node_modules/ws/lib/websocket.js:834:20)
    at Receiver.emit (node:events:390:28)
    at Receiver.dataMessage (/Users/jkrivine/Documents/git/blockchain/mangrove/packages/mangrove-solidity/node_modules/ws/lib/receiver.js:437:14)
    at Receiver.getData (/Users/jkrivine/Documents/git/blockchain/mangrove/packages/mangrove-solidity/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/Users/jkrivine/Documents/git/blockchain/mangrove/packages/mangrove-solidity/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/Users/jkrivine/Documents/git/blockchain/mangrove/packages/mangrove-solidity/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
```

**Comment by espendk** [comment]
You can might be able to work around it by doing:
```javascript
  const provider = new ethers.providers.WebSocketProvider(
    hre.network.config.url
  );

  const wallet = new ethers.Wallet(
    process.env["PRIVATE_KEY"],
    provider
  );

  const MgvAPI = await Mangrove.connect({
    signer: wallet
  });
```
That normally works for me.

The reason it works is because you are providing a `Signer` (in this case a `Wallet`) equipped with a `Provider` so mangrove.js just uses those directly and doesn't try to construct anything.

**Comment by espendk** [comment]
As to the error, it seems to indicate ethers.js is sending some invalid request to the endpoint. If the above workaround works, I'm not sure it's worth it to investigate further.

**Comment by jkrivine** [comment]
OK that works
