### ISSUE TITLE
Flaky test (potentially): mangrove-solidity Polygon mainnet Tests

### ISSUE THREAD

**Issue by dontrolle** [mangrovedao/mangrove#128]
The Polygon mainnet test-suite occasionally fails with provider errors, which we assume are problems with the Alchemy node, we use to access Polygon when forking; since the errors occur either as a timeout or a provider error in the setup-phase. 

We would like, however, to ensure that our tests-suite is as resilient against these issues, as possible. Therefore, this issue is logged to track our progress on improving this.

This run https://github.com/mangrovedao/mangrove/actions/runs/1688205285/attempts/1 - failed with a `ProviderError: Unable to complete request at this time.` 

The relevant parts of the log are copied below:

```
Run yarn run test:polygon-mainnet
$ token DAI ABI loaded. Address: 0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063
$ token USDC ABI loaded. Address: 0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174
$ token WETH ABI loaded. Address: 0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619
$ token CDAI ABI loaded. Address: 0x4eceddf62277ed78623f9a94995c680f8fd6c00e
$ token CUSDC ABI loaded. Address: 0x73cf8c5d14aa0ebc89f18272a568319f5bab6cbd
$ token CWETH ABI loaded. Address: 0x7ef18d0a9C3Fb1A716FF6c3ED0Edf52a2427F716
Mangrove is not pre deployed on polygon mainnet
Duplicate definition of ActionPaused (ActionPaused(string,bool), ActionPaused(address,string,bool))
polygon Compound ABI loaded. Unitroller address: 0x20CA53E2395FA571798623F1cFBD11Fe2C114c24
polygon Aave ABI loaded. LendingPool is at: 0x8dff5e27ea6b7ac08ebfdf9eb090f32ee9a30fcf
Nothing to compile
Running all test suites: basic,defensive,lender,offerProxy,persistent
  on network: polygon


  Running tests...
    1) "before all" hook for "Basic offer"

  Deploy defensive strategies
    2) "before all" hook for "Price fed strat"

  Deploy strategies
    3) "before all" hook for "Lender/borrower strat on compound"

  Deploy offerProxy
    4) "before all" hook for "Offer proxy on aave"

  Running tests...
    5) "before all" hook for "Swinging strat"


  0 passing (1m)
  5 failing

  1) Running tests...
       "before all" hook for "Basic offer":
     ProviderError: Unable to complete request at this time.
      at HttpProvider.request (node_modules/hardhat/internal/core/providers/http.js:50:23)
      at JsonRpcClient._send (node_modules/hardhat/internal/hardhat-network/jsonrpc/client.js:182:45)
      at JsonRpcClient._perform (node_modules/hardhat/internal/hardhat-network/jsonrpc/client.js:141:38)
      at JsonRpcClient.getTransactionCount (node_modules/hardhat/internal/hardhat-network/jsonrpc/client.js:77:21)
      at ForkStateManager.initializeGenesisAccounts (node_modules/hardhat/internal/hardhat-network/provider/fork/ForkStateManager.js:44:54)
      at Function.create (node_modules/hardhat/internal/hardhat-network/provider/node.js:123:36)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async HardhatNetworkProvider._init (node_modules/hardhat/internal/hardhat-network/provider/provider.js:170:32)
      at async HardhatNetworkProvider._send (node_modules/hardhat/internal/hardhat-network/provider/provider.js:129:9)
      at async HardhatNetworkProvider.request (node_modules/hardhat/internal/hardhat-network/provider/provider.js:72:26)

```

**Comment by dontrolle** [comment]
This failed run - https://github.com/mangrovedao/mangrove/runs/4965065031?check_suite_focus=true#step:11:127 - which at least resulted in a more meaningful Hardhat error 109 is logged under this same issue, as it it is assumed that any solution to this should involve being more resilient towards network issues.

Relevant snippet:

```
...
   1) Deploy strategies
       Lender/borrower strat on aave:
     HardhatError: HH109: Network connection timed out.
Please check your internet connection and networks config
      at HttpProvider._fetchJsonRpcResponse (node_modules/hardhat/internal/core/providers/http.js:133:23)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async HttpProvider.request (node_modules/hardhat/internal/core/providers/http.js:52:33)
      at async JsonRpcClient._send (node_modules/hardhat/internal/hardhat-network/jsonrpc/client.js:182:20)
      at async JsonRpcClient._perform (node_modules/hardhat/internal/hardhat-network/jsonrpc/client.js:141:27)
      at async ForkStateManager.getContractStorage (node_modules/hardhat/internal/hardhat-network/provider/fork/ForkStateManager.js:124:29)
      at async i (node_modules/@ethereumjs/vm/dist/evm/opcodes/functions.js:682:27)
      at async Interpreter.runStep (node_modules/@ethereumjs/vm/dist/evm/interpreter.js:92:13)
      at async Interpreter.run (node_modules/@ethereumjs/vm/dist/evm/interpreter.js:56:17)
...
```

**Comment by dontrolle** [comment]
Deprecated. Related to former `mangrove-solidity` repo and tests which are now ported to foundry.
